import Head from 'next/head'
import Image from 'next/image'
import Home from '../components/homebar'
import Link from 'next/link'

export default function index() {
  return (
    <div>
      <Head>
        <title>Off--</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/offavicon.ico" />
      </Head>
      <Home/>
    </div>
  )
}
