import Head from 'next/head'
import Image from 'next/image'
import Home from '../components/homebar'

export default function index() {
  return (
    <div>
      <Head>
        <title>Off-Wait</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home/>
    </div>
  )
}
